name: NEChatroom - iOS 
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build_chatroom_objc:
    name: Build NEChatroom Objc
    runs-on: macos-latest
    env:
      XC_PROJECT_NAME: ${{ 'NEChatroom-iOS-ObjC' }}
      XC_VERSION: ${{ '11.4' }}
      XC_SCHEME: ${{ 'NEChatroom-iOS-ObjC' }}
      XC_WORKSPACE: ${{ 'NEChatroom-iOS-ObjC.xcworkspace' }}
      XC_CONFIGURATION: ${{ 'release' }}
      XC_ARCHIVE_DIR: ${{ './product/archive' }}
      XC_IPA_DIR: ${{ './product/ipa' }}
      XC_EXPORT_OPTIONS_PATH: ${{ './Workflow/ExportOptions.plist' }}
      XC_CONFIG_STUB_SCRIPT_PATH: ${{ './Workflow/config_stub.py' }}

      ENCRYPTED_CERT_PATH: ${{ './Workflow/cert.p12.gpg' }}
      DECRYPTED_CERT_PATH: ${{ './Workflow/cert.p12' }}
      ENCRYPTED_PROVISION_PATH: ${{ './Workflow/enterpriseForWildCard.mobileprovision.gpg' }}
      DECRYPTED_PROVISION_PATH: ${{ './Workflow/enterpriseForWildCard.mobileprovision' }}
      CERT_ENC_PWD: ${{ secrets.CERT_ENC_PWD }}
      CERT_PWD: ${{ secrets.CERT_PWD }}
      PROVISION_ENC_PWD: ${{ secrets.PROVISION_ENC_PWD }}
      APP_KEY: ${{ secrets.APP_KEY }}
      API_BASE_URL: ${{ secrets.API_BASE_URL  }}
      KEYCHAIN: ${{ 'temp.keychain' }}
      APP_CONFIG_FILE_PATH: ${{ './NEChatroom-iOS-ObjC/AppKey.h' }}
    defaults:
      run:
        shell: bash
        working-directory: ./NEChatroom-iOS-ObjC/

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python 2.7
      uses: actions/setup-python@v2
      with:
          python-version: '2.7'
          
    - name: Config Stub
      run: 
        python $XC_CONFIG_STUB_SCRIPT_PATH $APP_CONFIG_FILE_PATH $APP_KEY $API_BASE_URL
    
    - name: Select Xcode
      run: 
        sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app

    - name: Install Dependencies
      run: pod install

    - name: Build
      run:
        xcodebuild build -workspace $XC_WORKSPACE -scheme $XC_SCHEME -configuration release -sdk iphoneos9.3;
